apiVersion: v1
kind: Service
metadata:
  name: pista-svc-nginx-web
  labels:
    app: nginx-web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "<LB_SG_ID>"
spec:
  type: LoadBalancer
  selector:
    app: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
