apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kubernetes/fastapi-app
images:
  - name: __ACCOUNT_ID__.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-app
    newTag: latest
