apiVersion: v1
kind: Service
metadata:
  name: rust-api
  labels:
    app: rust-api
spec:
  type: ClusterIP
  selector:
    app: rust-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
