apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kubernetes/nginx-web
images:
  - name: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/nginx-web
    newTag: latest
